// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4491.SimpleDriveTrain;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController simpleDriveTrainLeftFrontMotor;
    public static SpeedController simpleDriveTrainLeftRearMotor;
    public static SpeedController simpleDriveTrainRightFrontMotor;
    public static SpeedController simpleDriveTrainRightRearMotor;
    public static RobotDrive simpleDriveTrain4WheelDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        simpleDriveTrainLeftFrontMotor = new Victor(1, 1);
	LiveWindow.addActuator("SimpleDriveTrain", "LeftFrontMotor", (Victor) simpleDriveTrainLeftFrontMotor);
        
        simpleDriveTrainLeftRearMotor = new Victor(1, 2);
	LiveWindow.addActuator("SimpleDriveTrain", "LeftRearMotor", (Victor) simpleDriveTrainLeftRearMotor);
        
        simpleDriveTrainRightFrontMotor = new Victor(1, 3);
	LiveWindow.addActuator("SimpleDriveTrain", "RightFrontMotor", (Victor) simpleDriveTrainRightFrontMotor);
        
        simpleDriveTrainRightRearMotor = new Victor(1, 4);
	LiveWindow.addActuator("SimpleDriveTrain", "RightRearMotor", (Victor) simpleDriveTrainRightRearMotor);
        
        simpleDriveTrain4WheelDrive = new RobotDrive(simpleDriveTrainLeftFrontMotor, simpleDriveTrainLeftRearMotor,
              simpleDriveTrainRightFrontMotor, simpleDriveTrainRightRearMotor);
	
        simpleDriveTrain4WheelDrive.setSafetyEnabled(true);
        simpleDriveTrain4WheelDrive.setExpiration(0.1);
        simpleDriveTrain4WheelDrive.setSensitivity(0.5);
        simpleDriveTrain4WheelDrive.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
